name: Build docker image
description: Create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name of the image to create"
    required: false
    default: "academy"
  tag_name:
    description: "Tag of the image to create"
    required: false
runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
            echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
            echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
        echo "DOCKER_IMAGE_NAME=${{ inputs.image_name }}" >> $GITHUB_ENV
      shell: bash
    - run: docker build . --file ${{ inputs.dockerfile_path }} --tag joaomiguel899/$DOCKER_IMAGE_NAME:$TAG
      shell: bash