name: Build docker image
description: Create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name of the image to create"
    required: false
    default: "academy"
  tag_name:
    description: "Tag of the image to create"
    required: false
    default: $(date +%s)
runs:
  using: composite
  steps:
    - run: docker build . --file ${{ inputs.dockerfile_path }} --tag ${{ inputs.image_name }}:${{ inputs.tag_name }}
      shell: bash
