name: Push
description: Push Docker image
inputs:
  docker_username:
    description: "Docker username"
    required: true
runs:
  using: composite
  steps:
    - run: docker push ${{ inputs.docker_username }}/academy/$DOCKER_IMAGE_NAME:$TAG
      shell: bash