name: Push
description: Push Docker image
inputs:
  docker_username:
    description: "Docker username"
    required: true
  image_name:
    description: "Image name generated"
    required: true
runs:
  using: composite
  steps:
    - run: docker push ${{ inputs.docker_username }}/$DOCKER_IMAGE_NAME:$TAG
      shell: bash